In [1]:
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt

# Linear Algebra Exercise
## Preliminary demos: matrix multiplication, solving linear systems

### Matrix multiplication

In [3]:
A = np.array([
    [1, 0],
    [2, 1]
])

B = np.array([
    [5, 4],
    [-5, 1]
])

In [4]:
A

array([[1, 0],
       [2, 1]])

In [5]:
type(A)

numpy.ndarray

In [6]:
A * B # a multiplication per element

array([[  5,   0],
       [-10,   1]])

In [7]:
A @ B # the matrix multiplication!

array([[5, 4],
       [5, 9]])

In [8]:
B @ A

array([[13,  4],
       [-3,  1]])

In [9]:
matrix = np.array([
    [7, 3],
    [2, 5],
    [6, 8],
    [9, 0]
])

In [10]:
matrix.shape[1]

2

In [11]:
def multiply_matrices(a, b):
    # Assume A, B are matrices
    # we can use lists and check the length of the rows, cols, 
    # whether the lists are not jagged ect...
    # but it will be e little bit more lengthy and complex looking
    a_rows, a_cols = a.shape
    b_rows, b_cols = b.shape
    
    assert a_cols == b_rows
    
    result = np.zeros(shape = (a_rows, b_cols))
    
    for i in range(a_rows):
        for j in range(b_cols):
             # first way:
            #current_row = a[i, :]
            #current_col = b[:, j]
            #result[i, j]= current_row.dot(current_col)
            # second way:
            for k in range(a_cols):
                result[i, j] += a[i, k] * b[k, j]
    return result

In [12]:
multiply_matrices(A, B)

array([[5., 4.],
       [5., 9.]])

In [13]:
multiply_matrices(B, A)

array([[13.,  4.],
       [-3.,  1.]])

In [14]:
A = np.array([
    [7, 3],
    [2, 5],
    [6, 8],
    [9, 0]
])

B = np.array([
    [7, 4, 9],
    [8, 1, 5]
])

In [15]:
A @ B

array([[ 73,  31,  78],
       [ 54,  13,  43],
       [106,  32,  94],
       [ 63,  36,  81]])

In [16]:
multiply_matrices(A, B)

array([[ 73.,  31.,  78.],
       [ 54.,  13.,  43.],
       [106.,  32.,  94.],
       [ 63.,  36.,  81.]])

In [17]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
A[0, :] # 0th row
B[:, 0] # 0th column

array([5, 7])

In [18]:
A=[[1, 1],[-3, 1]]
b=[6,2]
    
np.linalg.inv(A).dot(b)
np.linalg.solve(A,b)

# Gaussian elimination - Method of Gauss-Gordan for find the inverse matrix

array([1., 5.])

### Linear systems of equations

In [19]:
# x + y = 6
# -3x + y = 2

In [20]:
A = [
    [1, 1],
    [-3, 1]
]

b = [6, 2]

In [21]:
np.linalg.solve(A, b)

array([1., 5.])

In [22]:
# 1x +  0y + 1z = 6
# 0x + -3y + 1z = 7
# 2x +  1y + 3z = 15

In [23]:
A = [
    [1, 0, 1],
    [0, -3, 1],
    [2, 1, 3]
]
b = [6, 7, 15]

In [24]:
np.linalg.solve(A, b)

array([ 2., -1.,  4.])

In [25]:
A = [[1, 1, -2, 1, 3, -1],
 [2, -1, 1, 2, 1, -3],
 [1, 3, -3, -1, 2, 1],
 [5, 2, -1, -1, 2, 1],
 [-3, -1, 2, 3, 1, 3],
 [4, 3, 1, -6, -3, -2]]
 
b = [4, 20, -15, -3, 16, -27]

In [26]:
np.linalg.solve(A, b)

array([ 1., -2.,  3.,  4.,  2., -1.])

In [27]:
# x + y = 2
# x + y = 3

# np.linalg.solve([[1, 1], [1, 1]], [2, 3])
# a linear system without results => singular matrix